# - https://bazel.build/external/overview#bzlmod
# - https://bazel.build/external/module
module(name = "d2lang", version = "0.0.0")

# Find the latest versions of module dependencies on:
#
# - https://registry.bazel.build/
#
bazel_dep(name = "rules_jvm_external", version = "6.8")
bazel_dep(name = "rules_java", version = "8.14.0")


# `use_extension` brings module extensions into scope for the module. All
# extensions brought into scope will execute after resolution of the module
# dependency graph.
#
# - https://bazel.build/external/extension
# - https://bazel.build/rules/lib/globals/module#use_extension
maven = use_extension("@rules_jvm_external//:extensions.bzl", "maven")

# Extensions may define "tag classes" that enable a module to configure
# attributes defining what it needs from the extension. Extension
# implementations will have access to this configuration data via the
# `module_ctx` object.
#
# - https://bazel.build/external/extension#extension_usage
# - https://bazel.build/external/extension#extension_definition
# - https://bazel.build/rules/lib/globals/bzl#tag_class
# - https://bazel.build/rules/lib/toplevel/attr.html
# - https://bazel.build/rules/lib/builtins/module_ctx#modules
# - https://bazel.build/rules/lib/builtins/bazel_module.html#tags
#
# For instructions on how to configure and use `rules_jvm_external`:
#
# - https://github.com/bazel-contrib/rules_jvm_external
# - https://github.com/bazel-contrib/rules_jvm_external/blob/master/docs/bzlmod.md
#
# These artifact coordinates are from https://repo1.maven.org/maven2
maven.install(
    artifacts = [
        "junit:junit:4.13.2",
        "com.github.pcj:google-options:jar:1.0.0",
        "com.google.auto.value:auto-value-annotations:1.11.0",
        "com.google.auto.value:auto-value:1.11.0",
        "com.google.code.findbugs:jsr305:3.0.2",
        "com.google.guava:guava:33.0.0-jre",
        "com.google.guava:guava-testlib:33.0.0-jre",
        "com.google.flogger:flogger:0.8",
        "com.google.flogger:flogger-system-backend:0.8",
        "com.google.truth:truth:1.4.4",
        "com.google.testparameterinjector:test-parameter-injector:1.14",
    ],
    fetch_javadoc = True,
    fetch_sources = True,
    repositories = [
        "https://repo1.maven.org/maven2",
    ],
)

# A module must bring any required repositories that are created by a module
# extension into scope by calling `use_repo` on the module extension object.
#
# - https://bazel.build/external/extension#extension_usage
# - https://bazel.build/rules/lib/globals/module#use_repo
use_repo(maven, "maven")

# For how to update these values:
# - https://github.com/google/bazel-common?tab=readme-ov-file#using-bazel-common
# - https://bazel.build/external/module#non-registry_overrides
# - https://bazel.build/rules/lib/globals/module#git_override

bazel_dep(name = "google_bazel_common")
git_override(
    module_name = "google_bazel_common",
    commit = "1a0839806501e7f7e8dd7663644895dbc593827e",
    remote = "https://github.com/google/bazel-common",
)
