; This was generated by T100CodeGenerator, mostly

; To assemble: python [path]/assembler.py dcode -t
org 0x9000
jmp __START
  CONST_helloworld_0: dm "hello world\0"
  _anint: db 00,00,00,00

__START:

  ; SOURCE: printf("%s", \"hello world\")
  lxi H, CONST_helloworld_0
  call 0x11A2

