java_library(
    name = "testing",
    testonly = 1,
    srcs = [
        "PhaseSubject.java",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//src/com/plasstech/lang/d2:yet_another_compiler",
        "//src/com/plasstech/lang/d2/common",
        "//src/com/plasstech/lang/d2/phase:phase_name",
        "//src/com/plasstech/lang/d2/phase:state",
        "@maven//:com_google_truth_truth",
        "@maven//:junit_junit",
    ],
)
