
java_library(name="nodes", 
             srcs=glob(["*Node.java"]),
	     deps=["//src/com/plasstech/lang/d2/type:vartype",
	           "//src/com/plasstech/lang/d2/common:position",
	          ],
	     )
