
java_library(name="position",
	     srcs=["Position.java"],
	     visibility=["//:__subpackages__"],
	     )

java_library(name="exceptions",
	     srcs=["D2RuntimeException.java"],
	     visibility=["//:__subpackages__"],
	     )
