java_library(name="common",
             srcs=glob(["*.java"]),
             visibility=["//visibility:public"],
             deps=[
              "@maven//:com_github_pcj_google_options",
             ],
             )
