java_library(
    name = "testing",
    srcs = [
        "EmitterSubject.java",
        "LocationUtils.java",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//src/com/plasstech/lang/d2/codegen",
        "//src/com/plasstech/lang/d2/codegen:locations",
        "//src/com/plasstech/lang/d2/type:storage",
        "//src/com/plasstech/lang/d2/type:symbols",
        "//src/com/plasstech/lang/d2/type:var_types",
        "@maven//:com_google_guava_guava",
        "@maven//:com_google_truth_truth",
    ],
)
