java_library(
    name = "testing",
    testonly = 1,
    srcs = ["OpcodeSubject.java"],
    visibility = ["//visibility:public"],
    deps = [
        "//src/com/plasstech/lang/d2/codegen:location",
        "//src/com/plasstech/lang/d2/codegen/il",
        "//src/com/plasstech/lang/d2/common",
        "@maven//:com_google_guava_guava",
        "@maven//:com_google_truth_truth",
    ],
)
