java_library(
    name="lex",
    srcs=glob(["*.java"]),
    deps=[
        "//src/com/plasstech/lang/d2/common",
        "@maven//:com_google_guava_guava",
    ],
    visibility=["//visibility:public"],
)

