java_library(
    name = "lex",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//src/com/plasstech/lang/d2/common",
        "@maven//:com_google_guava_guava",
    ],
)
