java_library(
    name = "optimize",
    srcs = glob(
        ["*.java"],
    ),
    visibility = ["//visibility:public"],
    deps = [
        "//src/com/plasstech/lang/d2/codegen:trimmers",
        "//src/com/plasstech/lang/d2/phase",
        "//src/com/plasstech/lang/d2/phase:state",
        "@maven//:com_google_guava_guava",
    ],
)
